name: checks
on: [push, pull_request]
jobs:
  checks:
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1', '8.2']
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: phive
      - name: Install CMSimple_XH
        run: |
          curl -fsSL -o CMSimple_XH-1.7.5.zip https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.7.5/CMSimple_XH-1.7.5.zip
          unzip -q CMSimple_XH-1.7.5.zip
      - name: Patch CMSimple_XH
        run: cd cmsimplexh/cmsimple && sed -i 's/@return int The number of bytes written, or false on failure\./@return int\|false/g' functions.php
      - name: Checkout Plib_XH
        uses: actions/checkout@v3
        with:
          repository: cmb69/plib_xh
          path: cmsimplexh/plugins/plib
      - name: Checkout Coco_XH
        uses: actions/checkout@v3
        with:
          path: 'cmsimplexh/plugins/coco'
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: cmsimplexh/plugins/coco/tools
          key: tools-${{matrix.php}}-${{hashFiles('cmsimplexh/plugins/coco/.phive')}}
      - if: ${{steps.cache-tools.outputs.cache-hit != 'true'}}
        name: phive install
        run: cd cmsimplexh/plugins/coco && phive --no-progress install --copy --force-accept-unsigned --trust-gpg-keys 0x0F9684B8B16B7AB0,0x31C7E470E2138192,0xCF1A108D0E7AE720,0xD5F0CB76E2DD74F8
      - name: composer install
        run: cd cmsimplexh/plugins/coco && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/coco && PATH=tools:vendor/bin:$PATH phing sniff
      - name: phing stan
        run: cd cmsimplexh/plugins/coco && PATH=tools:vendor/bin:$PATH phing stan
      - name: phing test
        run: cd cmsimplexh/plugins/coco && PATH=tools:vendor/bin:$PATH phing test
